/**
 * Tentackle - a framework for java desktop applications
 * Copyright (C) 2001-2008 Harald Krake, harald@krake.de, +49 7722 9508-0
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// $Id: AboutDialog.java 377 2008-07-28 08:40:47Z harald $
// Created on February 18, 2004, 12:34 PM

package org.tentackle.appworx;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.text.MessageFormat;
import java.util.StringTokenizer;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 * About dialog.<br>
 * 
 * Displays the application's logo (icon), versioning information
 * and a memory/GC-button.
 * 
 * @author harald
 */
public class AboutDialog extends org.tentackle.ui.FormDialog {
  
  private Thread gcUpdater;     // update GC-Button thread
  private String text;          // the text
  private Icon   logo;          // logo icon
  
  
  /**
   * Creates an about dialog.
   *
   * @param text the application text, description
   * @param logo the icon logo, null = default icon
   */
  public AboutDialog(String text, Icon logo) {
    this.text = text;
    this.logo = logo;
    if (logo == null) {
      this.logo = new ImageIcon(getClass().getResource("/org/tentackle/appworx/images/loginLogo.png"));   // NOI18N
    }
    setup();
  }
  
  /**
   * initialization code common to all constructors
   */
  private void setup()  {
    initComponents();
    
    applicationTextArea.setText(text);
    tentackleVersionLabel.setText("Tentackle " + org.tentackle.util.Version.VERSION);  // NOI18N
    javaVersionLabel.setText("Java " + System.getProperty("java.version"));  // NOI18N
    
    Dimension size = imageLabel.getPreferredSize();
    int width = size.width;
    int height = size.height;
    layeredPane.setPreferredSize(size);
    imageLabel.setBounds(0, 0, width, height);
    logoPanel.setBounds(0, 0, width, height);
    int logoWidth = logo.getIconWidth();
    int logoHeight = logo.getIconHeight();
    logoLabel.setIcon(logo);
    logoLabel.setBounds((width/2 - logoWidth)/2, (height - logoHeight)/2, logoWidth, logoHeight);
    
    // the first word of "text" becomes part of the dialog title
    StringTokenizer stok = new StringTokenizer(text);
    if (stok.hasMoreTokens()) {
      setTitle(MessageFormat.format(Locales.bundle.getString("About_{0}"), stok.nextToken()));
    }
    
    gcUpdater = new Thread() {
      @Override
      public void run() {
        while (!isInterrupted()) {
          try {
            sleep(1000);
          } 
          catch (InterruptedException ex) {
            return;   // stop thread
          }
          EventQueue.invokeLater(new Runnable() {
            public void run() {
              gcButton.refresh();
            }
          });
        }
      }
    };

    pack();
    
    gcUpdater.start();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    layeredPane = new javax.swing.JLayeredPane();
    imageLabel = new javax.swing.JLabel();
    infoPanel = new org.tentackle.ui.FormPanel();
    applicationTextArea = new org.tentackle.ui.FormTextArea();
    tentackleVersionLabel = new javax.swing.JLabel();
    javaVersionLabel = new javax.swing.JLabel();
    gcButton = new org.tentackle.ui.GCButton();
    closeButton = new org.tentackle.ui.FormButton();
    jLabel1 = new javax.swing.JLabel();
    logoPanel = new org.tentackle.ui.FormPanel();
    logoLabel = new javax.swing.JLabel();

    setAutoPosition(true);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tentackle/appworx/images/login.png")));
    imageLabel.setBounds(0, 0, -1, -1);
    layeredPane.add(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

    infoPanel.setOpaque(false);
    applicationTextArea.setChangeable(false);
    applicationTextArea.setForeground(java.awt.Color.orange);
    applicationTextArea.setFont(new java.awt.Font("Dialog", 1, 12));
    applicationTextArea.setOpaque(false);

    tentackleVersionLabel.setForeground(new java.awt.Color(204, 204, 255));
    tentackleVersionLabel.setText("Tentackle Build xxx");

    javaVersionLabel.setForeground(new java.awt.Color(204, 204, 255));
    javaVersionLabel.setText("java xxx");

    gcButton.setBorder(null);
    gcButton.setBorderPainted(false);
    gcButton.setFocusable(false);
    gcButton.setFont(new java.awt.Font("Dialog", 0, 12));
    gcButton.setForeground(new java.awt.Color(204, 204, 255));
    gcButton.setOpaque(false);
    gcButton.setText("? / ? M");

    closeButton.setBackground(new java.awt.Color(204, 204, 255));
    closeButton.setMargin(new java.awt.Insets(1, 4, 1, 4));
    closeButton.setText(Locales.bundle.getString("close")); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });

    jLabel1.setForeground(new java.awt.Color(204, 204, 255));
    jLabel1.setText(Locales.bundle.getString("Memory:")); // NOI18N

    javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
    infoPanel.setLayout(infoPanelLayout);
    infoPanelLayout.setHorizontalGroup(
      infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(infoPanelLayout.createSequentialGroup()
        .addContainerGap(276, Short.MAX_VALUE)
        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tentackleVersionLabel)
            .addComponent(applicationTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(javaVersionLabel)
            .addGroup(infoPanelLayout.createSequentialGroup()
              .addComponent(jLabel1)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(gcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    infoPanelLayout.setVerticalGroup(
      infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
        .addContainerGap(98, Short.MAX_VALUE)
        .addComponent(applicationTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tentackleVersionLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(javaVersionLabel)
        .addGap(7, 7, 7)
        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(gcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(56, 56, 56)
        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    infoPanel.setBounds(0, 0, 500, 350);
    layeredPane.add(infoPanel, javax.swing.JLayeredPane.PALETTE_LAYER);

    logoPanel.setLayout(null);

    logoPanel.setOpaque(false);
    logoLabel.setFont(new java.awt.Font("SansSerif", 1, 12));
    logoPanel.add(logoLabel);
    logoLabel.setBounds(45, 60, 140, 200);

    logoPanel.setBounds(0, 0, 500, 350);
    layeredPane.add(logoPanel, javax.swing.JLayeredPane.MODAL_LAYER);

    getContentPane().add(layeredPane, java.awt.BorderLayout.CENTER);

  }// </editor-fold>//GEN-END:initComponents

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    dispose();
  }//GEN-LAST:event_closeButtonActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    gcUpdater.interrupt();
  }//GEN-LAST:event_formWindowClosing
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.tentackle.ui.FormTextArea applicationTextArea;
  private org.tentackle.ui.FormButton closeButton;
  private org.tentackle.ui.GCButton gcButton;
  private javax.swing.JLabel imageLabel;
  private org.tentackle.ui.FormPanel infoPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel javaVersionLabel;
  private javax.swing.JLayeredPane layeredPane;
  private javax.swing.JLabel logoLabel;
  private org.tentackle.ui.FormPanel logoPanel;
  private javax.swing.JLabel tentackleVersionLabel;
  // End of variables declaration//GEN-END:variables
  
}
