/**
 * Tentackle - a framework for java desktop applications
 * Copyright (C) 2001-2008 Harald Krake, harald@krake.de, +49 7722 9508-0
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// $Id: AppDbCursorProgressDialog.java 336 2008-05-09 14:40:20Z harald $

package org.tentackle.appworx;

import org.tentackle.plaf.PlafGlobal;

/**
 * Progress dialog for {@link AppDbCursor}.
 * <p>
 * The modal dialog is shown if more than {@link QbfParameter#warnRowCount}
 * rows are retrieved and the user answers the question to retrieve more
 * with "yes". The progress dialog shows and updates the numbers of rows retrieved
 * and provides an abort button.
 * 
 * @author harald
 */
public class AppDbCursorProgressDialog extends org.tentackle.ui.FormDialog {
  
  
  private AppDbCursor cursor;
  
  /**
   * Creates a progress dialog.
   * 
   * @param cursor the database cursor
   */
  public AppDbCursorProgressDialog(AppDbCursor cursor) {
    this.cursor = cursor;
    initComponents();
  }
  
  
  /**
   * Shows the modal dialog.
   */
  public void showDialog()  {
    pack();
    setVisible(true);
  }

  
  /**
   * Updates and displays the row count.
   * 
   * @param rowCount
   */
  public void updateRowCount(int rowCount) {
    rowCountField.setIntValue(rowCount);
  }
  
  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    infoPanel = new org.tentackle.ui.FormPanel();
    jLabel1 = new javax.swing.JLabel();
    rowCountField = new org.tentackle.ui.IntegerFormField();
    buttonPanel = new org.tentackle.ui.FormPanel();
    abortButton = new org.tentackle.ui.FormButton();

    setAutoPosition(true);
    setTitle(Locales.bundle.getString("Loading_objects...")); // NOI18N
    setModal(true);

    infoPanel.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText(Locales.bundle.getString("objects_read_so_far:")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    infoPanel.add(jLabel1, gridBagConstraints);

    rowCountField.setColumns(10);
    rowCountField.setChangeable(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
    infoPanel.add(rowCountField, gridBagConstraints);

    getContentPane().add(infoPanel, java.awt.BorderLayout.CENTER);

    abortButton.setIcon(PlafGlobal.getIcon("working"));
    abortButton.setText(Locales.bundle.getString("abort")); // NOI18N
    abortButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abortButtonActionPerformed(evt);
      }
    });
    buttonPanel.add(abortButton);

    getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void abortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortButtonActionPerformed
    cursor.setAbortRequested(true);
  }//GEN-LAST:event_abortButtonActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.tentackle.ui.FormButton abortButton;
  private org.tentackle.ui.FormPanel buttonPanel;
  private org.tentackle.ui.FormPanel infoPanel;
  private javax.swing.JLabel jLabel1;
  private org.tentackle.ui.IntegerFormField rowCountField;
  // End of variables declaration//GEN-END:variables
  
}
