/**
 * Tentackle - a framework for java desktop applications
 * Copyright (C) 2001-2008 Harald Krake, harald@krake.de, +49 7722 9508-0
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// $Id: DefaultQbfPanel.java 336 2008-05-09 14:40:20Z harald $
// Created on September 18, 2002, 4:57 PM

package org.tentackle.appworx;

import java.awt.EventQueue;


/**
 * The default qbf panel for the normtext search.
 */
public class DefaultQbfPanel extends org.tentackle.appworx.QbfPanel {
  
  /**
   * Creates a DefaultQbfPanel for a given qbf parameter.
   *
   * @param parameter the qbf parameter
   */  
  public DefaultQbfPanel(QbfParameter parameter) {
    super(parameter);
    initComponents();
  }
  
  
  @Override
  public void setInitialFocus() {
    searchPatternField.requestFocusLater();
  }  
  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    searchPatternField = new org.tentackle.ui.StringFormField();

    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText(Locales.bundle.getString("Pattern:")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jLabel1, gridBagConstraints);

    searchPatternField.setAutoSelect(true);
    searchPatternField.setColumns(20);
    searchPatternField.setConvert('^');
    searchPatternField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchPatternFieldActionPerformed(evt);
      }
    });
    searchPatternField.addValueListener(new org.tentackle.ui.ValueListener() {
      public void valueChanged(org.tentackle.ui.ValueEvent evt) {
        searchPatternFieldValueChanged(evt);
      }
      public void valueEntered(org.tentackle.ui.ValueEvent evt) {
        searchPatternFieldValueEntered(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
    add(searchPatternField, gridBagConstraints);

  }// </editor-fold>//GEN-END:initComponents

  private void searchPatternFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatternFieldActionPerformed
    EventQueue.invokeLater(new Runnable() {
      public void run() {
        getParameter().pattern = searchPatternField.getText();
        fireActionPerformed();
      }
    });
  }//GEN-LAST:event_searchPatternFieldActionPerformed

  private void searchPatternFieldValueEntered(org.tentackle.ui.ValueEvent evt) {//GEN-FIRST:event_searchPatternFieldValueEntered
    getParameter().pattern = searchPatternField.getText();
  }//GEN-LAST:event_searchPatternFieldValueEntered

  private void searchPatternFieldValueChanged(org.tentackle.ui.ValueEvent evt) {//GEN-FIRST:event_searchPatternFieldValueChanged
    searchPatternField.setText(getParameter().pattern);
  }//GEN-LAST:event_searchPatternFieldValueChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private org.tentackle.ui.StringFormField searchPatternField;
  // End of variables declaration//GEN-END:variables
  
}

