/*
 * HistoryTableDialog.java
 *
 * Created on June 8, 2005, 12:42 PM
 */

package org.tentackle.appworx;

import java.awt.Window;
import org.tentackle.plaf.PlafGlobal;

/**
 * Shows the history for a given AppDbObject.
 *
 * @author harald
 */
public class HistoryTableDialog extends org.tentackle.ui.FormDialog {
  
  
  public HistoryTableDialog(Window owner, boolean modal) {
    super(owner, modal);
    initComponents();
  }
  
  
  public HistoryTableDialog(boolean modal) {
    this(null, modal);
  }
  
  
  
  /**
   * @param obj to show the history for.
   */
  public void showDialog(AppDbObject obj) {
    setTitle(Locales.bundle.getString("History_for") + " " + obj.getTreeText());
    historyPanel.setHistoryForObject(obj);
    pack();
    closeButton.requestFocusInWindow();
    setVisible(true);
  }
  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    buttonPanel = new org.tentackle.ui.FormPanel();
    closeButton = new org.tentackle.ui.FormButton();
    historyPanel = new org.tentackle.appworx.HistoryTablePanel();

    setAutoPosition(true);
    closeButton.setIcon(PlafGlobal.getIcon("close"));
    closeButton.setMnemonic('c');
    closeButton.setText(Locales.bundle.getString("close")); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });

    buttonPanel.add(closeButton);

    getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(historyPanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    dispose();
  }//GEN-LAST:event_closeButtonActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.tentackle.ui.FormPanel buttonPanel;
  private org.tentackle.ui.FormButton closeButton;
  private org.tentackle.appworx.HistoryTablePanel historyPanel;
  // End of variables declaration//GEN-END:variables
  
}
