/**
 * Tentackle - a framework for java desktop applications
 * Copyright (C) 2001-2008 Harald Krake, harald@krake.de, +49 7722 9508-0
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// $Id: SecurityRemoteDelegate.java 367 2008-07-20 16:49:01Z harald $

package org.tentackle.appworx.rmi;

import org.tentackle.appworx.Security;
import java.rmi.RemoteException;
import java.util.List;
import org.tentackle.appworx.ContextDb;
import org.tentackle.util.TrackedArrayList;

/**
 * Remote delegate for {@link Security}.
 * 
 * @author harald
 */
public interface SecurityRemoteDelegate extends AppDbObjectRemoteDelegate {
 
  public void assertRemoteSecurityManagerInitialized(ContextDb contextDb) throws RemoteException;
  
  // @wurblet inclrmi Include --missingok .$classname/methods

  // Code generated by wurblet. Do not edit!//GEN-BEGIN:inclrmi

  public List<Security> selectByGrantId(ContextDb contextDb, long grantId) throws RemoteException;
  public TrackedArrayList<Security> selectByObject(ContextDb contextDb, long objectId, String objectClass) throws RemoteException;
  public int deleteByGrantee(long grantId) throws RemoteException;
  public int deleteByObject(long objectId, String objectClass) throws RemoteException;
  public int deleteObjectRulesByObjectClass(String objectClass) throws RemoteException;
  public int deleteObjectRulesByObjectClassAndContext(String objectClass, long contextId, String contextClass) throws RemoteException;
  public int deleteObjectRulesByGrantClass(String grantClass) throws RemoteException;
  public int deleteObjectRulesByGrantClassAndContext(String grantClass, long contextId, String contextClass) throws RemoteException;

  // End of wurblet generated code.//GEN-END:inclrmi
  
}
